// webui/src/views/Login.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import apiClient from '../api/client';
import { Shield, User, Lock, AlertCircle } from 'lucide-react';

const Login = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const response = await apiClient.post('/login', {
        username,
        password,
      });

      if (response.data && response.data.message === 'ok') {
        // 登录成功，跳转到仪表盘
        navigate('/');
      }
    } catch (err) {
      console.error('Login error:', err);
      setError(err.response?.data?.error || '登录失败，请检查用户名和密码');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-blue-900 to-gray-900 flex items-center justify-center p-4">
      {/* Background decoration */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-blue-500 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-pulse"></div>
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-purple-500 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-pulse delay-1000"></div>
      </div>

      {/* Login Card */}
      <div className="relative w-full max-w-md">
        {/* Logo */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-600 rounded-2xl mb-4 shadow-lg">
            <Shield className="text-white" size={32} />
          </div>
          <h1 className="text-3xl font-bold text-white mb-2">PPanel</h1>
          <p className="text-gray-400">Linux Server Management Panel</p>
        </div>

        {/* Form Card */}
        <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-8 shadow-2xl border border-white/20">
          <h2 className="text-xl font-semibold text-white mb-6">Sign In</h2>

          {error && (
            <div className="mb-6 flex items-center gap-2 bg-red-500/20 border border-red-500/50 text-red-200 px-4 py-3 rounded-lg">
              <AlertCircle size={20} />
              <span>{error}</span>
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-6">
            {/* Username */}
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Username
              </label>
              <div className="relative">
                <User className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
                <input
                  type="text"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  className="w-full pl-10 pr-4 py-3 bg-white/5 border border-white/20 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="Enter your username"
                  required
                  autoComplete="username"
                />
              </div>
            </div>

            {/* Password */}
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Password
              </label>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
                <input
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full pl-10 pr-4 py-3 bg-white/5 border border-white/20 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="Enter your password"
                  required
                  autoComplete="current-password"
                />
              </div>
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              disabled={loading}
              className="w-full py-3 px-4 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-800 disabled:cursor-not-allowed text-white font-semibold rounded-lg transition-all duration-200 flex items-center justify-center gap-2 shadow-lg hover:shadow-xl"
            >
              {loading ? (
                <>
                  <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  <span>Signing in...</span>
                </>
              ) : (
                <span>Sign In</span>
              )}
            </button>
          </form>

          {/* Footer */}
          <div className="mt-6 text-center">
            <p className="text-gray-400 text-sm">
              Default credentials: <span className="text-gray-300 font-mono">admin / admin</span>
            </p>
          </div>
        </div>

        {/* Version */}
        <div className="mt-6 text-center text-gray-500 text-xs">
          PPanel v1.0.0 &copy; 2024
        </div>
      </div>
    </div>
  );
};

export default Login;

// frontend/src/Login.vue
<script setup>

import {
    ref,
    nextTick,
    onMounted
} from "vue"

import {
    useRouter
} from "vue-router"



const router = useRouter()


const username = ref("")

const password = ref("")


const error = ref("")

const loading = ref(false)


const usernameInput = ref(null)




async function login(){


    if(loading.value)
        return



    error.value=""



    if(!username.value || !password.value){

        error.value="请输入用户名和密码"

        return

    }



    loading.value=true



    try{


        let res =
        await fetch(
            "/api/login",
            {

                method:"POST",

                credentials:"include",

                headers:{

                    "Content-Type":
                    "application/json"

                },


                body:JSON.stringify({

                    username:
                    username.value,


                    password:
                    password.value

                })

            }
        )




        if(res.ok){


            router.push("/")


        }
        else{


            error.value="用户名或密码错误"


        }



    }
    catch(e){


        error.value="服务器连接失败"


    }
    finally{


        loading.value=false


    }


}





function enterLogin(e){


    if(e.key==="Enter"){

        login()

    }


}





onMounted(()=>{


    nextTick(()=>{

        usernameInput.value.focus()

    })


})



</script>




<template>


<div
class="login-page"
>


<div
class="login-box"
>


<div class="logo">

🐧

</div>



<h1>
Linux Panel
</h1>



<p class="subtitle">
服务器管理控制台
</p>




<form
@submit.prevent="login"
>



<input

ref="usernameInput"

v-model="username"

placeholder="用户名"

autocomplete="username"

/>





<input

v-model="password"

type="password"

placeholder="密码"

autocomplete="current-password"

@keyup="enterLogin"

/>





<div
class="error"
v-if="error"
>

{{error}}

</div>





<button
:disabled="loading"
>


{{

loading
?
"登录中..."
:
"登录"

}}



</button>



</form>



</div>



</div>


</template>





<style scoped>


.login-page{


height:100vh;

display:flex;

justify-content:center;

align-items:center;


background:

linear-gradient(
135deg,
#1e293b,
#334155
);


}





.login-box{


width:360px;

padding:40px;


background:white;


border-radius:18px;


box-shadow:

0 15px 40px
rgba(0,0,0,.25);


text-align:center;


}





.logo{


font-size:55px;

margin-bottom:10px;


}




h1{


margin:0;

font-size:30px;


}




.subtitle{


color:#888;

margin:10px 0 30px;


}





input{


width:100%;

box-sizing:border-box;


padding:14px;


margin-bottom:15px;


border-radius:8px;


border:1px solid #ddd;


font-size:16px;


}





input:focus{


outline:none;


border-color:#2563eb;


}





button{


width:100%;


padding:14px;


border:none;


border-radius:8px;


background:#2563eb;


color:white;


font-size:17px;


cursor:pointer;


}





button:hover{


background:#1d4ed8;


}





button:disabled{


opacity:.6;


cursor:not-allowed;


}





.error{


color:#ef4444;


margin-bottom:15px;


font-size:14px;


}



</style>
